version: "3.4"

services:
    rabbitmq:
        hostname: rabbitmq
        image: rabbitmq:latest
        networks:
            - main
        ports:
            - "5672:5672"
        restart: on-failure

    postgres:
        hostname: postgres
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        networks:
            - main
        ports:
            - "5432:5432"
        restart: on-failure
        volumes:
            - postgresql-data:/var/lib/postgresql/data

    app:
        image: alannazhou/django
        environment:
            - DJANGO_SETTINGS_MODULE=flick.settings.production
        depends_on:
            - postgres
            - rabbitmq
        expose:
            - "8000"
        hostname: app
        networks:
            - main
        restart: on-failure
        volumes:
            - static:/static

    celery_worker:
        image: alannazhou/celery
        depends_on:
            - app
            - postgres
            - rabbitmq
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    cpus: "0.50"
                    memory: 50M
                reservations:
                    cpus: "0.25"
                    memory: 20M
        hostname: celery_worker
        networks:
            - main
        restart: on-failure

    nginx:
        image: alannazhou/nginx
        depends_on:
            - app
        networks:
            - main
        ports:
            - "80:80"
        restart: on-failure
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d
            - ./wait-for:/bin/wait-for
            - static:/var/www/app/static

networks:
    main:

volumes:
    postgresql-data:
    static:
